/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonClick: typeof import('./src/components/common/ButtonClick.vue')['default']
    CalculationEarningRisk: typeof import('./src/components/CalculationEarningRisk.vue')['default']
    DropDownList: typeof import('./src/components/common/DropDownList.vue')['default']
    EarningResults: typeof import('./src/components/ALM/EarningResults.vue')['default']
    GridData: typeof import('./src/components/GridData.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ProgressStatus: typeof import('./src/components/ProgressStatus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveCancel: typeof import('./src/components/SaveCancel.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
    ToolBarBottom: typeof import('./src/components/ToolBarBottom.vue')['default']
    ToolBarMiddle: typeof import('./src/components/ToolBarMiddle.vue')['default']
    ToolBarTop: typeof import('./src/components/ToolBarTop.vue')['default']
    TopMenu: typeof import('./src/components/TopMenu.vue')['default']
    Validation: typeof import('./src/components/Validation.vue')['default']
  }
}
